version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    day: "saturday"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 10
  assignees:
  - mprins
  labels:
    - dependencies
    - build-infra

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "21:00"
    timezone: "Europe/Berlin"
  labels:
    - build-infra
