tag-template: "schemaspy-maven-plugin-$NEXT_PATCH_VERSION"
name-template: v$NEXT_PATCH_VERSION 🎁

version-template: "$MAJOR.$MINOR.$PATCH"

template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: 🚀 New features and improvements
      when:
        labels:
        - enhancement
  - title: 🔨 Security fixes en updates
      when:
        labels:
          - security
  - title: 🐛 Bug Fixes
      when:
        labels:
          - bug
          - fix
          - bugfix
          - regression
  - title: 📖 Documentation updates
      when:
        label: documentation
  - title: 🚨 Removed / ⚠️ Deprecated
      when:
        labels:
          - removed
          - deprecated
  - title: 🚦 Tests and Infrastructure
      when:
        labels:
          - infrastructure
      collapse-after: 10
  - title: 🔨 Dependency updates
      when:
        label: dependencies
      collapse-after: 10

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
