name: OWASP dependency check

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
        java_dist: ["temurin"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}
          cache: maven

      - name: OWASP Dependency Check
        continue-on-error: true
        run: mvn package -Dmaven.test.skip=true org.owasp:dependency-check-maven:check -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=7 -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/dependency-check-report.sarif
