name: Maven Site

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven

      - name: Build Site with Maven
        run: mvn site -Dmaven.test.skip=true -B -V -fae -q -DnvdApiKey=${{ secrets.NVD_API_KEY }}
